[MIG] base_time_window: Migration to 18.0
Kimkhoi3010/server-tools pull request #1
Opened 2024-09-20 11:32 UTC by Kimkhoi3010

2024-09-24 07:48 UTC, nguyenminhchien requested changes
Migrate `test_base_time_window` as well. Both modules in 1 PR.

2024-09-24 07:48 UTC, nguyenminhchien commented on base_time_window/models/time_weekday.py
remove the method name_get() . From version 17.0, we don't need to override this one any more. Check [Migration-to-version-17.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-to-do-in-the-migration) for more information

2024-09-24 07:48 UTC, nguyenminhchien commented on base_time_window/README.rst
README.rst mentions to a module `test_base_window` which's available in 14.0: [test_base_window](https://github.com/OCA/server-tools/tree/14.0/test_base_time_window).

Please migrate that module to 18.0 as well.

2024-09-24 07:48 UTC, nguyenminhchien commented on base_time_window/models/time_window_mixin.py
> +    # TODO patch api.constrains with field here?
Handle this #TODO.

2024-10-10 07:41 UTC, nguyenminhchien requested changes
- Squash these commits
![image](https://github.com/user-attachments/assets/b86714cc-cf5a-414d-8e7a-1ee37cc45859)
- Create new commit `[MIG] test_base_time_window: Migration to 18.0` for migrating test_base_time_window

2024-10-10 07:41 UTC, nguyenminhchien commented on base_time_window/models/time_weekday.py
> +    _sql_constraints = [("name_uniq", "UNIQUE(name)", _("Name must be unique"))]
```suggestion
    _sql_constraints = [("name_uniq", "UNIQUE(name)", "Name must be unique")]
```

2024-10-10 07:43 UTC, nguyenminhchien commented
Port or add [this commit](https://github.com/OCA/server-tools/pull/2213/commits/a6d621c611d4f32b1731683b0560290b31de70dc) to blacklist

2024-10-11 03:55 UTC, closed without merging

2024-10-21 07:48 UTC, nilshamerlinck commented
what's the status on this one?
did you have a look at `https://github.com/OCA/server-tools/pull/3030`?

2024-10-22 05:00 UTC, Kimkhoi3010 commented
Hi @nguyenminhchien @nilshamerlinck, I created a new PR [OCA#3087](https://github.com/OCA/server-tools/pull/3087) to OCA/server-tools.
(This PR was closed auto after rebased)

2024-10-22 05:24 UTC, Kimkhoi3010 commented
Hi @nguyenminhchien, @nilshamerlinck can you have take a look?
I create a new PR https://github.com/Kimkhoi3010/server-tools/pull/8