[18.0][MIG] base_technical_user: Migration to 18.0
Kimkhoi3010/server-tools pull request #2
Opened 2024-09-23 04:29 UTC by Kimkhoi3010

2024-09-24 08:41 UTC, nguyenminhchien requested changes
Port the commits mentioned in the card

2024-10-01 08:49 UTC, nilshamerlinck commented
@Kimkhoi3010 better finish ongoing tasks instead of starting new ones ;-) what's the status on these ports?

2024-10-02 04:27 UTC, nguyenminhchien approved these changes

2024-10-07 08:04 UTC, nilshamerlinck commented
same here: 18.0 migration commit should appear last

2024-10-09 06:44 UTC, nguyenminhchien approved these changes

2024-10-15 03:54 UTC, closed without merging