[18.0][MIG] attachment_unindex_content: Migration to 18.0
Kimkhoi3010/server-tools pull request #3
Opened 2024-10-07 05:36 UTC by Kimkhoi3010

2024-10-07 09:37 UTC, thienvh332 requested changes

2024-10-07 09:37 UTC, thienvh332 commented on attachment_unindex_content/readme/CREDITS.md
> +- Camptocamp.
```suggestion
The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp.

```

2024-10-14 07:46 UTC, nilshamerlinck commented
@thienvh332 can you update your review, Khoi took into account your change requests

2024-10-14 07:49 UTC, thienvh332 approved these changes
LGTM

2024-10-16 08:16 UTC, closed without merging