[18.0][MIG] base_time _window: Migration to 18.0
Kimkhoi3010/server-tools pull request #4
Opened 2024-10-25 09:36 UTC by Kimkhoi3010

2024-10-28 03:49 UTC, nguyenminhchien approved these changes

2024-10-28 08:24 UTC, nilshamerlinck commented on base_time_window/readme/CREDITS.md
> +The migration of this module from 17.0 to 18.0 was financially supported by:
why not both? please don't erase the past

2024-10-28 08:25 UTC, nilshamerlinck commented on .eslintrc.yml
probably need to rebase your 18.0 branch

2024-10-28 08:26 UTC, nilshamerlinck requested changes
oca PR is red

2024-10-29 03:59 UTC, closed without merging

2024-10-29 04:01 UTC, Kimkhoi3010 commented
Sorry @nilshamerlinck, @nguyenminhchien, this PR close by my mistake.
This PR [#5](https://github.com/Kimkhoi3010/server-tools/pull/5) takes over