[18.0][MIG] base_time_window: Migration to 18.0
Kimkhoi3010/server-tools pull request #8
Opened 2024-10-22 05:23 UTC by Kimkhoi3010

It found only 1 commit  to port but it was ignored, i added them to blacklist:
[/b4ac749](https://github.com/Kimkhoi3010/server-tools/pull/4)

2024-10-22 08:30 UTC, nguyenminhchien requested changes
- I left 1 comment.
- You could review the PR server-tools/pull/3030 if having time.

2024-10-22 08:30 UTC, nguyenminhchien commented on base_time_window/models/time_window_mixin.py
> +    partner_id = fields.Many2one(
I don't think this's a good solution. If you cannot find the better solution, keep it as it is.

2024-10-23 02:20 UTC, nguyenminhchien requested changes

2024-10-23 02:20 UTC, nguyenminhchien commented on base_time_window/models/time_window_mixin.py
> -    # TODO patch api.constrains with field here?
@Kimkhoi3010 don't remove this line, keep it just in case.

2024-10-23 02:20 UTC, nguyenminhchien commented on base_time_window/models/time_window_mixin.py
> +            if check_field and record[check_field]:
No need checking here! If no `_time_window_overlap_check_field` defined, the Developer will face an Error right away.
So, he need to inherit this feature properly.

2024-10-23 03:05 UTC, nguyenminhchien requested changes

2024-10-23 03:05 UTC, nguyenminhchien commented on base_time_window/models/time_window_mixin.py
> +                    self.env._(f"{record.display_name} overlaps {other.display_name}")
```suggestion
                    self.env._("%s overlaps %s", record.display_name, other.display_name)
```

2024-10-24 02:58 UTC, nguyenminhchien requested changes
I just pull the latest odoo 18.0 codebase.
I started the server and face 2 issues:
1. Translation issue
```
  File "/home/chien/code/oca/server-tools/18.0/base_time_window/models/time_weekday.py", line 7, in <module>
    class TimeWeekday(models.Model):
  File "/home/chien/code/oca/server-tools/18.0/base_time_window/models/time_weekday.py", line 23, in TimeWeekday
    _sql_constraints = [("name_uniq", "UNIQUE(name)", _("Name must be unique"))]
  File "/home/chien/code/odoo/odoo/master/odoo/tools/translate.py", line 609, in get_text_alias
    module, lang = _get_translation_source(1)
  File "/home/chien/code/odoo/odoo/master/odoo/tools/translate.py", line 598, in _get_translation_source
    lang = lang or _get_lang(frame, default_lang)
  File "/home/chien/code/odoo/odoo/master/odoo/tools/translate.py", line 589, in _get_lang
    _logger.log(log_level, 'no translation language detected, skipping translation %s', frame, stack_info=True)
```
2. Import test class
```
2024-10-24 02:56:06,745 93809 WARNING v18c_base_time_window odoo_test_helper.fake_model_loader: Wrong Import in module base_time_window, the class <class 'odoo.addons.base_time_window.tests.test_models.TestTimeWindowModel'> have been already imported.
Please take a look to the README on how to import test class 
```

2024-10-24 03:04 UTC, nguyenminhchien commented
Error when testing test_base_time_window:
```
2024-10-24 03:03:03,955 96581 INFO v18c_base_time_window odoo.addons.test_base_time_window.tests.test_base_time_window: Starting TestTimeWindow.test_00 ... 
2024-10-24 03:03:03,959 96581 ERROR v18c_base_time_window odoo.sql_db: bad query: b'\n                SELECT\n                    id\n                FROM\n                    test_partner_time_window w\n                    join test_partner_time_window_time_weekday_rel as d\n                    on d.test_partner_time_window_id = w.id\n                WHERE\n                    NUMRANGE(w.time_window_start::numeric,\n                        w.time_window_end::numeric) &&\n                            NUMRANGE(10.0::numeric, 12.0::numeric)\n                    AND w.id != 1\n                    AND d.time_weekday_id in (1)\n                    AND w.False = 1;'
ERROR: column w.false does not exist
LINE 14:                     AND w.False = 1;
                                 ^
```

2024-10-25 07:55 UTC, closed without merging

2024-10-25 08:06 UTC, Kimkhoi3010 commented
Hi @nguyenminhchien, I created a new Internal PR: https://github.com/Kimkhoi3010/server-tools/pull/9